# Generated by Django 2.0.3 on 2018-07-18 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0064_productvariant_handle_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='popular', to='product.Category')),
            ],
        ),
    ]
