# Generated by Django 2.0.3 on 2018-07-19 22:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('popular_categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='popularcategory',
            options={'permissions': (('view', 'Can view popular categories'), ('edit', 'Can edit popular categories'))},
        ),
        migrations.AddField(
            model_name='popularcategory',
            name='added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
